import type { Metadata } from "next";
import { Cormorant_Garamond, DM_Mono } from "next/font/google";
import "./globals.css";
import AudioInit from "@/components/AudioInit";
import MuteButton from "@/components/MuteButton";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "600"],
  style: ["normal", "italic"],
  variable: "--font-cormorant",
  display: "swap",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: ["300", "400"],
  variable: "--font-dm-mono",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://aihaikus.com"),
  title: "AI Haikus — 50 Bitcoin Ordinal Inscriptions",
  description:
    "A permanent archive of 50 haikus generated by early AI and inscribed on the Bitcoin blockchain on February 11th, 2023. By @888mooncat.",
  openGraph: {
    title: "AI Haikus",
    description:
      "Preserving the first thoughts of artificial intelligence, sealed permanently on Bitcoin.",
    url: "https://aihaikus.com",
    siteName: "AI Haikus",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Haikus",
    description:
      "Preserving the first thoughts of artificial intelligence, sealed permanently on Bitcoin.",
    creator: "@888mooncat",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable} ${dmMono.variable} antialiased`}
    >
      <body className="min-h-screen bg-bg text-text-primary">
        {children}
        <AudioInit />
        <MuteButton />
      </body>
    </html>
  );
}
